backend:
  name: metastrofipsuxis
  repo: [username]/antoniosvamvakas-blog
  branch: main
  
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Τίτλος", name: "title", widget: "string"}
      - {label: "Ημερομηνία", name: "date", widget: "datetime"}
      - {label: "Περιεχόμενο", name: "body", widget: "markdown"}
